### ISSUE TITLE
Free space in Ucloud

### ISSUE THREAD

**Issue by Suncatcher** [ucloud/ucloud-sdk-python3#16]
Hi,
just wanted to ask how much cloud space do they offer for free?

Thanks

**Comment by esplendo** [comment]
20G free object storage.
https://www.ucloud.cn/site/product/ufile.html

**Comment by esplendo** [comment]
promotion：https://www.ucloud.cn/site/global.html

**Comment by Suncatcher** [comment]
OK, thanks. I registered but at the top I see red exclamation sign with words

根据《网安法》，您尚未完成实名认证无法购买和使用资源，请完成 实名认证

Google gives following translation:

> According to the "Net Security Law", you have not completed the real-name certification and cannot purchase and use resources. Please complete the real-name certification.

Is it true? The verification by ID is mandatory?

**Comment by Junping-W** [comment]
Yes. Do you have a passport? A passport can be submitted for certification.

**Comment by Junping-W** [comment]
If you have any question，please add my WeChat or WhatsApp Number 18917085427 .

**Comment by Suncatcher** [comment]
So it is impossible to use ucloud without verification?

**Comment by Junping-W** [comment]
Yes,that‘s right.
